name: Upload Website
#on denotes on what event to perform this action.
#Here, we are saying to perform this on pushes to branch 'main'
on:
  push:
    branches:
      - main

#This job, titled Deploy, will run on the latest version of Ubuntu 
# (also the cheapest platform to perform Github Actions). It will 
# - check out the 'main' branch
# - Download and install Node.js, adding it to the PATH. Download any NPM
# dependencies.
# - npm run build does what is specified in package.json. Primarily, building 
# or prep tasks for the project.
# - Configures AWS creds stored as secrets in repo.
# Pushes build to S3 bucket using AWS sync.
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      #- name: Install Dependecies
      #  run: npm install

      #- name: Build Static File
      #  run: npm run build

      #- name: Configure AWS Credentials
        # uses: aws-actions/configure-aws-credentials@v1
        #with:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: us-east-2

      - name: Deploy static site to S3 bucket
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws s3 sync ./build s3://{mateomartinez.net}
